version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    env_file:
      - .env.docker
    build: .
    container_name: notes-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    
  frontend:
    build: ./frontend
    depends_on:
      - app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
  
volumes:
  pgdata: